config:
  aws:region: us-east-1
  nexus-ai-aws-baseline:projectName: nexus-ai
  nexus-ai-aws-baseline:environment: staging
  nexus-ai-aws-baseline:vpcCidr: 10.81.0.0/16
  nexus-ai-aws-baseline:allowedIngressCidrs:
    - 10.0.0.0/8
